Support provider state teardown
pact-foundation/pact-net pull request #422
Opened 2022-10-31 15:19 UTC by sprengo

2022-11-07 18:42 UTC, adamrodger requested changes

2022-11-07 18:42 UTC, adamrodger commented on src/PactNet.Abstractions/Verifier/IPactVerifierSource.cs
> +        IPactVerifierSource WithProviderStateUrl(Uri providerStateUri, bool teardown = false);
This is a breaking API change, when though it's optional, so needs to be a separate overload instead of an optional parameter

2022-11-07 18:42 UTC, adamrodger commented on src/PactNet.Abstractions/Verifier/IPactVerifierSource.cs
> +    {
Are there some line ending changes here or something? Unchanged lines appear to be marked as change

2022-11-07 18:44 UTC, adamrodger commented
Please could you also change the commit message to follow the conventional commits style?

2022-11-07 18:48 UTC, adamrodger commented
I'm wondering what to do about the API for this because there's another bool parameter on the FFI call, and we should probably add support for that at the same time.

If we just add the one parameter then we'll make adding a second parameter awkward, because that would be (Uri, bool, bool). If you just wanted to set the second bool without the first then you couldn't, because they would both have the signature (Uri, bool).

We should perhaps make those two parameters enums instead of using bools there so that we can add the appropriate overloads and communicate the intent of those parameters more clearly.

2022-11-08 11:06 UTC, sprengo commented
Any suggestions how to name the enums?

ProviderStateInvocationBehavior { SetupOnly, WithTeardown }
ProviderStateTransmissionType { QueryParams, Body }

2023-01-11 17:21 UTC, philek commented
I would go the simplest route with only one overload of (Uri, bool, bool). The options are simple and there's no need to complicate it with enums and additional overloads. At most add default values so you can only override one.

2023-02-12 15:18 UTC, adamrodger commented
Provider state configuration support added in https://github.com/pact-foundation/pact-net/commit/c2ec3cc4b1a4f65b99aaaa7625af49bf6fbc4700

2023-02-12 15:18 UTC, closed without merging